version: "3.7"
services:
   db:
     image: mysql:5.7
     container_name: wordpress-db
     ports:
       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: r00t
       MYSQL_DATABASE: wordpress
       MYSQL_USER: usr-wordpress
       MYSQL_PASSWORD: pwd-wordpress
     
   wordpress:
     image: wordpress
     container_name: wordpress
     ports:
       - "8080:80"
     depends_on:
       - db
     environment:
        WORDPRESS_DB_HOST: wordpress-db
        WORDPRESS_DB_USER: usr-wordpress
        WORDPRESS_DB_PASSWORD: pwd-wordpress
        WORDPRESS_DB_NAME: wordpress


