apiVersion: v1
kind: Service
metadata:
  labels:
    app: shipping
  name: shipping # o que define o endereço. http://shipping:3001
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app: shipping
