kind: Deployment
apiVersion: apps/v1
metadata:
  name: shipping
  labels:
    app: shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping
  template:
    metadata:
      labels:
        app: shipping
    spec:
      containers:
      - name: shipping-pod
        image: rodneybarreto/minipets_shipping-api:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8082